#Imports 
import math
import time
#Variables
#Functions
#PHASE ONE User Prerequisites
#Introduce project to the User
print('***ADOPT A SHELTER PET***')
time.sleep(1)
print('This program walks you through') 
time.sleep(2)
print('a logical series of considerations')
time.sleep(2)
print('and simple calculations')
time.sleep(2)
print('to successfully adopt a shelter pet.')
time.sleep(2)
print("First, you'll answer questions") 
time.sleep(2)
print('regarding your lifestyle, budget,')
time.sleep(2)
print('free time, and living space.') 
time.sleep(2)
print("After the Q&A section, we'll take a quick look")
time.sleep(2)
print('at research regarding shelter pets')
time.sleep(2)
print('in the United States.')
time.sleep(2)
print("We'll also look at what people are saying") 
time.sleep(2)
print('about shelter pets on Twitter.')
time.sleep(2)
print("Finally, we'll use YOUR prerequisites")
time.sleep(2)
print('to search for YOUR perfect pet match')
time.sleep(2)
print('at an imaginary Animal Shelter.')
time.sleep(2)
print("Let's get started!")
time.sleep(2)
print('***INTRODUCE YOURSELF***')
time.sleep(2)
firstname = input('Enter your first name: ')
time.sleep(2)
print('Hello', firstname,'.', "Nice to meet you.")
time.sleep(2)
print('Please answer these questions honestly.')
#FINANCIAL COMMITMENT
print('***FINANCIAL COMMITMENT***')
time.sleep(2)
print('You told us you plan to adopt a shelter DOG.')
time.sleep(2)
print('According to ROVER.com')
time.sleep(2)
print('the annual cost of owning a dog -') 
time.sleep(2)
print('adopted from a shelter,') 
time.sleep(2)
print('not purchased from a breeder -')
time.sleep(2) 
print('runs $650 to $1000 per year.')
time.sleep(2)
print('This estimate covers basic costs like food,')
time.sleep(2)
print('necessary vaccines, toenail trims,') 
time.sleep(2)
print('flea, tick, and heartworm protection,')
time.sleep(2)
print('bedding, collars, leash/harness, and toys.')
time.sleep(2)
print("Let's also factor in the adoption fee")
time.sleep(2)
print('and the cost to spay/neuter your pet.')
time.sleep(2)
print("Let's estimate an annual cost between")
time.sleep(2)
print('$800 and $1200 to be safe.') 
time.sleep(2)
print('Can you afford this financial commitment?')
time.sleep(2)
inthemoney = input('Type y for YES or n for NO: ')
time.sleep(2)
#Game will end if user answers NO
#If Y, proceed
#If N, skip to EXIT statement at end of program