#Imports 
import math
import time
#Variables
hoursperday = 24
#Functions
#PHASE ONE User Prerequisites
#Introduce project to the User
print('***ADOPT A SHELTER PET***\n')
time.sleep(2)
print('This program walks you through') 
time.sleep(2)
print('a logical series of considerations')
time.sleep(2)
print('and simple calculations')
time.sleep(2)
print('to successfully adopt a shelter pet.\n')
time.sleep(2)
print("First, you'll answer questions") 
time.sleep(2)
print('regarding your lifestyle, budget,')
time.sleep(2)
print('free time, and living space.\n') 
time.sleep(2)
print("After the Q&A section,")
time.sleep(2)
print("we'll take a quick look")
time.sleep(2)
print('at research regarding shelter pets')
time.sleep(2)
print('in the United States.\n')
time.sleep(2)
print("We'll also look at") 
time.sleep(2)
print('what people are saying')
time.sleep(2)
print('about shelter pets on Twitter.\n')
time.sleep(2)
print("Finally, we'll use YOUR prerequisites")
time.sleep(2)
print('to search for YOUR perfect pet match')
time.sleep(2)
print('at an imaginary Animal Shelter.\n')
time.sleep(2)
print("Let's get started!\n")
time.sleep(2)
print('***INTRODUCE YOURSELF***\n')
time.sleep(2)
firstname = input('Enter your first name: ')
time.sleep(2)
print('\nHello ' + firstname + '.')
print("It's nice to meet you.")
time.sleep(2)
print('\n***QUESTIONS AND ANSWERS***')
time.sleep(2)
#FINANCIAL COMMITMENT
print('\n***FINANCIAL COMMITMENT***')
time.sleep(2)
print('\nYou told us you plan to adopt a shelter DOG.\n')
time.sleep(2)
print('According to ROVER.com,')
time.sleep(2)
print('the annual cost of owning a dog -') 
time.sleep(2)
print('adopted from a shelter,') 
time.sleep(2)
print('not purchased from a breeder -')
time.sleep(2) 
print('runs $650 to $1000 per year.\n')
time.sleep(2)
print('This estimate covers basic costs like food,')
time.sleep(2)
print('necessary vaccines, toenail trims,') 
time.sleep(2)
print('flea, tick, and heartworm protection,')
time.sleep(2)
print('bedding, collars, leash/harness, and toys.\n')
time.sleep(2)
print("Let's also factor in the adoption fee")
time.sleep(2)
print('and the cost to spay/neuter your pet.\n')
time.sleep(2)
print("Let's estimate an annual cost between")
time.sleep(2)
print('$1000 and $1500 to be safe.\n') 
time.sleep(2)
print('Can you afford this financial commitment?')
time.sleep(2)
money = input('Type y for YES or n for NO: ')
time.sleep(2)
#Game will end if user answers NO
#If Y, proceed
if money == 'n':
    print('\nThank you for the honest assessment of your financial situation.')
    time.sleep(2)
    print('At this time, we cannot recommend adopting a shelter pet.')
    time.sleep(2)
    print('Please reconsider at a time when you have more wiggle room in your budget.')
    time.sleep(2)
    print('There will always be AWESOME dogs looking for FOREVER homes.')
    exit()
else:
    print("\nExcellent! You're one step closer to sucessfully adopting a shelter pet.")
time.sleep(2)
#FREE TIME PER DAY
print('\n***FREE TIME PER DAY***')
time.sleep(2)
print('\nInstructions: Enter the number of hours you spend') 
time.sleep(2)
print('on each of the activities below, per day.') 
time.sleep(2)
print('Hours spent is calculated using whole numbers.\n')
time.sleep(2)
sleep = input('Hours spent sleeping per day: ')
time.sleep(2)
cook = input('Hours spent cooking + eating per day: ') 
time.sleep(2)
groom = input('Hours spent on showering, hair, makeup, shaving, etc. daily: ')
time.sleep(2)
commute = input('Hours spent commuting daily: ') 
time.sleep(2)
work = input('Hours spent working daily: ')
time.sleep(2)
errands = input('Hours spent running errands daily: ')
time.sleep(2)
gym = input('Hours spent working out daily: ')
time.sleep(2)
children = input('Hours spent caring for children or other adults daily: ')
time.sleep(2)
community = input('Hours spent volunteering, coaching, or at church daily: ')
time.sleep(2)
print("\nWhew! Aren't you exhausted?\n")
time.sleep(2)
print('The American Humane Society recommends')
print('that pet owners have') 
print('a minimum of 4 free hours per day')
print('to devote to caring for, training, and playing with their pets.\n')
hoursfordog = int(hoursperday) - int(sleep) - int(cook) - int(groom) - int(commute) - int(work) - int(errands) - int(gym) - int(children) - int(community)
print('You indicated you have ' + str(hoursfordog) + ' hours of FREE time daily.')